# Generated by Django 3.1.3 on 2021-02-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210121_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
