# Generated by Django 3.1.5 on 2021-01-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210113_1412'),
        ('account', '0002_auto_20210116_1226'),
    ]

    operations = [
    ]
