# Generated by Django 3.1.3 on 2020-11-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='active',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
