# Generated by Django 3.1.3 on 2020-12-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20201130_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'User', 'verbose_name_plural': 'All Users'},
        ),
    ]
