# Generated by Django 3.1.3 on 2020-12-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customer_remember_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
