# Generated by Django 3.1.3 on 2020-12-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_delete_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='buyer',
        ),
    ]
