# Generated by Django 3.1.3 on 2021-02-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockup',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
