# Generated by Django 3.1.3 on 2021-02-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0002_mockup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockup',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mockup',
            unique_together={('slug', 'title')},
        ),
    ]
