# Generated by Django 3.1.3 on 2020-12-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201218_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_label',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
