<<<<<<< HEAD
# Generated by Django 3.1.3 on 2021-01-04 07:58
=======
# Generated by Django 3.1.3 on 2020-12-31 23:09
>>>>>>> 03e32a683f403d4edca3549b3d37cb67ed454704

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0010_remove_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon'),
        ),
    ]
