# Generated by Django 3.1.3 on 2021-01-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210113_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='seller',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
