# Generated by Django 3.1.3 on 2021-02-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='design',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
