# Generated by Django 3.1.3 on 2021-02-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_auto_20210219_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='digital_product',
            field=models.FileField(help_text='Customer will download this file upon succesfull payment', null=True, upload_to='digital_products/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='price for this digital product', max_digits=12, null=True),
        ),
    ]
