# Generated by Django 3.1.3 on 2021-02-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_auto_20210219_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='design_categories', to='designs.Design_Category'),
        ),
    ]
