# Generated by Django 3.1.3 on 2021-03-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sz',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sz',
            name='sz',
        ),
        migrations.DeleteModel(
            name='Clr',
        ),
        migrations.DeleteModel(
            name='Sz',
        ),
    ]
