# Generated by Django 3.1.3 on 2020-11-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
