# Generated by Django 3.1.5 on 2021-03-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='uuid1',
            new_name='uuid2',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='uuid1',
            new_name='uuid2',
        ),
        migrations.AddField(
            model_name='design',
            name='uuid3',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='uuid3',
            field=models.UUIDField(null=True),
        ),
    ]
