# Generated by Django 3.1.3 on 2021-01-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='color',
            name='updated_at',
        ),
    ]
