# Generated by Django 3.1.3 on 2021-01-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='technique',
        ),
    ]
