# Generated by Django 3.1.5 on 2021-01-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='color',
            name='texture',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='price',
        ),
        migrations.RemoveField(
            model_name='techniquebase',
            name='fonts',
        ),
        migrations.DeleteModel(
            name='Font',
        ),
    ]
