# Generated by Django 3.1.3 on 2021-03-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0002_auto_20210304_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='price for this printing method', max_digits=12)),
                ('row_no', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='szs', to='essentials.product')),
                ('sz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.size')),
            ],
            options={
                'ordering': ['row_no'],
            },
        ),
        migrations.CreateModel(
            name='Clr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.color')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clrs', to='essentials.product')),
            ],
            options={
                'ordering': ['row_no'],
            },
        ),
    ]
