# Generated by Django 3.1.3 on 2020-12-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0002_auto_20201128_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='mockup_group',
        ),
        migrations.DeleteModel(
            name='Mockup_Group',
        ),
    ]
