# Generated by Django 3.1.3 on 2021-01-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0002_remove_product_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='product',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='product',
        ),
    ]
