# Generated by Django 3.1.5 on 2021-03-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0002_auto_20210301_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='uuid1',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='uuid1',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='design',
            name='uuid2',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='uuid2',
        ),
    ]
