# Generated by Django 3.1.5 on 2021-03-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0002_auto_20210301_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='uuid2',
            new_name='uuid1',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='uuid2',
            new_name='uuid1',
        ),
    ]
