# Generated by Django 3.1.3 on 2021-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0003_clr_sz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.75, help_text='price for this printing method', max_digits=12),
        ),
        migrations.AlterField(
            model_name='variant',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
