# Generated by Django 3.1.5 on 2021-03-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0003_auto_20210301_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='uuid1',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='uuid1',
        ),
    ]
