# Generated by Django 3.1.3 on 2020-12-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0004_auto_20201214_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='title',
        ),
    ]
