# Generated by Django 3.1.3 on 2021-01-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0004_auto_20210125_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='placement',
        ),
        migrations.AddField(
            model_name='method',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='essentials.product'),
        ),
        migrations.AddField(
            model_name='placement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='essentials.product'),
        ),
        migrations.DeleteModel(
            name='Mockup',
        ),
    ]
