# Generated by Django 3.1.3 on 2021-01-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0005_auto_20210106_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='items',
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='itemattributevalue',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='itemattributevalue',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemtypeattributevalue',
            name='attribute_value',
        ),
        migrations.RemoveField(
            model_name='itemtypeattributevalue',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='itemvariant',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemvariantvalues',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemvariantvalues',
            name='value',
        ),
        migrations.RemoveField(
            model_name='itemvariantvalues',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='variantimage',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionItem',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemAttributeValue',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
        migrations.DeleteModel(
            name='ItemTypeAttributeValue',
        ),
        migrations.DeleteModel(
            name='ItemVariant',
        ),
        migrations.DeleteModel(
            name='ItemVariantValues',
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
