# Generated by Django 3.1.3 on 2021-03-04 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0005_auto_20210304_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clr',
            name='clr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.color'),
        ),
        migrations.AlterField(
            model_name='sz',
            name='sz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.size'),
        ),
    ]
