# Generated by Django 3.1.3 on 2021-01-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0005_placement_placementbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='price for this placement', max_digits=12),
        ),
    ]
