# Generated by Django 3.1.3 on 2020-12-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0005_remove_variant_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_tag',
            field=models.ImageField(blank=True, upload_to='color_tags/'),
        ),
    ]
