# Generated by Django 3.1.5 on 2021-03-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0005_auto_20210301_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='uuid5',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='uuid5',
            new_name='uuid',
        ),
    ]
