# Generated by Django 3.1.3 on 2021-01-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0006_auto_20210106_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='technique',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='technique',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='essentials.Technique'),
        ),
        migrations.AddField(
            model_name='technique',
            name='technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essentials.techniquebase'),
        ),
    ]
