# Generated by Django 3.1.3 on 2021-03-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0006_auto_20210304_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sz',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='price for this size', max_digits=12, null=True),
        ),
    ]
