# Generated by Django 3.1.5 on 2021-03-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0006_auto_20210301_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='uuid3',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='uuid3',
        ),
    ]
