# Generated by Django 3.1.3 on 2021-01-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0006_auto_20210125_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.techniquebase'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='essentials.product'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.color'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.size'),
        ),
    ]
