# Generated by Django 3.1.3 on 2021-01-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0007_auto_20210106_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={},
        ),
    ]
