# Generated by Django 3.1.3 on 2020-12-18 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('essentials', '0007_auto_20201215_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_product_img', models.ImageField(upload_to='end_product_imgs/')),
                ('image', models.ImageField(upload_to='designs/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='essentials.variant')),
            ],
        ),
    ]
