# Generated by Django 3.1.3 on 2021-01-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0007_auto_20210125_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='height',
            field=models.CharField(blank=True, default='300px', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='left',
            field=models.CharField(blank=True, default='150px', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='top',
            field=models.CharField(blank=True, default='75px', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='width',
            field=models.CharField(blank=True, default='200px', max_length=10, null=True),
        ),
    ]
