# Generated by Django 3.1.3 on 2021-01-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0007_auto_20210113_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, help_text='texture has priorty on color code', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='texture',
            field=models.ImageField(blank=True, help_text='texture has priorty on color code', null=True, upload_to='textures/'),
        ),
    ]
