# Generated by Django 3.1.3 on 2021-03-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0007_auto_20210304_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='clr',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='price for this color', max_digits=12),
        ),
    ]
