# Generated by Django 3.1.3 on 2021-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0008_clr_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(null=True, related_name='products', to='essentials.Category'),
        ),
    ]
