# Generated by Django 3.1.3 on 2021-01-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0008_auto_20210125_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='placement',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='essentials.placementbase'),
        ),
    ]
