# Generated by Django 3.1.3 on 2021-01-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0008_auto_20210113_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, help_text='texture has priorty on color code. either color code or texture will be color option to customers', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='texture',
            field=models.ImageField(blank=True, help_text='texture has priorty on color code. either color code or texture will be color option to customers', null=True, upload_to='textures/'),
        ),
    ]
