# Generated by Django 3.1.3 on 2021-01-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0009_auto_20210106_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='technique',
        ),
    ]
