# Generated by Django 3.1.5 on 2021-01-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0009_auto_20210115_1626'),
        ('essentials', '0002_auto_20210116_1241'),
    ]

    operations = [
    ]
