# Generated by Django 3.1.3 on 2021-01-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0009_auto_20210125_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClrBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('row_no', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Clr -Test',
                'verbose_name_plural': 'Clrs -Test',
                'ordering': ['row_no'],
            },
        ),
        migrations.CreateModel(
            name='SzBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('row_no', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Sz -Test',
                'verbose_name_plural': 'Szs -Test',
                'ordering': ['row_no'],
            },
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['size', 'color']},
        ),
        migrations.CreateModel(
            name='Sz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='szs', to='essentials.product')),
                ('sz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.szbase')),
            ],
            options={
                'ordering': ['row_no'],
            },
        ),
        migrations.CreateModel(
            name='Clr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(blank=True, help_text='texture has priorty on color code. either color code or texture will be color option to customers', max_length=40, null=True)),
                ('texture', models.ImageField(blank=True, help_text='texture has priorty on color code. either color code or texture will be color option to customers', null=True, upload_to='textures/')),
                ('row_no', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='essentials.clrbase')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clrs', to='essentials.product')),
            ],
            options={
                'ordering': ['row_no'],
            },
        ),
    ]
