# Generated by Django 3.1.3 on 2021-01-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0010_merge_20210116_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, help_text='texture has priorty on color code. either color code or texture will be color option to customers', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='texture',
            field=models.ImageField(blank=True, help_text='texture has priorty on color code. either color code or texture will be color option to customers', null=True, upload_to='textures/'),
        ),
        migrations.AddField(
            model_name='placement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='price for this placement', max_digits=12),
        ),
        migrations.AddField(
            model_name='techniquebase',
            name='fonts',
            field=models.ManyToManyField(blank=True, null=True, related_name='technique_bases', to='essentials.Font'),
        ),
    ]
