# Generated by Django 3.1.3 on 2021-01-26 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0010_auto_20210126_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clr',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='clr',
            name='texture',
        ),
        migrations.AddField(
            model_name='clrbase',
            name='color_code',
            field=models.CharField(blank=True, help_text='texture has priorty on color code. either color code or texture will be color option to customers', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='clrbase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clrbase',
            name='texture',
            field=models.ImageField(blank=True, help_text='texture has priorty on color code. either color code or texture will be color option to customers', null=True, upload_to='textures/'),
        ),
        migrations.AddField(
            model_name='clrbase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='szbase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='szbase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
