# Generated by Django 3.1.3 on 2021-03-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0010_auto_20210304_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
