# Generated by Django 3.1.3 on 2021-01-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0010_method_placement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='technique',
        ),
    ]
