# Generated by Django 3.1.3 on 2021-01-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0011_remove_variant_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='product',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='Placement',
        ),
    ]
