# Generated by Django 3.1.3 on 2021-01-12 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0011_remove_variant_technique'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="e.g. 'front' or 'back'", max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='method',
            name='name',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='name',
        ),
        migrations.AddField(
            model_name='method',
            name='technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essentials.techniquebase'),
        ),
        migrations.AddField(
            model_name='placement',
            name='placement',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='essentials.placementbase'),
            preserve_default=False,
        ),
    ]
