# Generated by Django 3.1.3 on 2021-01-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0011_auto_20210126_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='sz',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='price for this printing method', max_digits=12),
        ),
    ]
