# Generated by Django 3.1.3 on 2021-03-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0012_auto_20210305_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
