# Generated by Django 3.1.3 on 2021-01-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0012_auto_20210112_1641'),
        ('essentials', '0012_auto_20210112_1622'),
    ]

    operations = [
    ]
