# Generated by Django 3.1.3 on 2021-01-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0012_auto_20210118_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_tag',
            field=models.ImageField(blank=True, upload_to='color_tags/'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, help_text='texture has priorty on color code. either color code or texture will be color option to customers', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='texture',
            field=models.ImageField(blank=True, help_text='texture has priorty on color code. either color code or texture will be color option to customers', null=True, upload_to='textures/'),
        ),
        migrations.AlterField(
            model_name='method',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='essentials.product'),
        ),
        migrations.AlterField(
            model_name='method',
            name='technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essentials.techniquebase'),
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essentials.techniquebase')),
            ],
        ),
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('active', models.BooleanField(default=True)),
                ('item_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='essentials.color')),
            ],
            options={
                'ordering': ('item_color',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='technique',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='essentials.Technique'),
        ),
    ]
