# Generated by Django 3.1.5 on 2021-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0013_auto_20210118_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='bottom',
            field=models.CharField(blank=True, help_text='100px', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='height',
            field=models.CharField(blank=True, help_text='400px', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='left',
            field=models.CharField(blank=True, help_text='150px', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='right',
            field=models.CharField(blank=True, help_text='150px', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='top',
            field=models.CharField(blank=True, help_text='600px', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='width',
            field=models.CharField(blank=True, help_text='200px', max_length=12, null=True),
        ),
    ]
