# Generated by Django 3.1.3 on 2021-01-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0013_auto_20210118_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='left',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='top',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='width',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
