# Generated by Django 3.1.3 on 2021-03-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0013_variant_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clr',
            options={'ordering': ['row_no', 'created_at']},
        ),
    ]
