# Generated by Django 3.1.3 on 2020-12-31 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0014_auto_20201231_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['size', 'color', 'technique']},
        ),
    ]
