# Generated by Django 3.1.3 on 2021-03-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0014_auto_20210308_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sz',
            options={'ordering': ['sz']},
        ),
    ]
