# Generated by Django 3.1.3 on 2021-01-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0014_auto_20210119_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
