# Generated by Django 3.1.3 on 2021-01-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0015_clrbase_szbase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClrBase',
        ),
        migrations.DeleteModel(
            name='SzBase',
        ),
    ]
