# Generated by Django 3.1.3 on 2021-01-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0015_placement_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color_tag',
        ),
    ]
