# Generated by Django 3.1.3 on 2020-12-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0015_auto_20201231_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': []},
        ),
        migrations.RemoveField(
            model_name='size',
            name='row_no',
        ),
    ]
