# Generated by Django 3.1.3 on 2021-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0016_remove_color_color_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['row_no']},
        ),
        migrations.AlterModelOptions(
            name='placement',
            options={'ordering': ['row_no']},
        ),
        migrations.AddField(
            model_name='method',
            name='row_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='row_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
