# Generated by Django 3.1.5 on 2021-01-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0017_auto_20210120_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_tag',
            field=models.ImageField(blank=True, null=True, upload_to='color_tags/'),
        ),
    ]
