# Generated by Django 3.1.3 on 2021-01-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0018_color_color_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['color']},
        ),
        migrations.RemoveField(
            model_name='color',
            name='color_tag',
        ),
    ]
