# Generated by Django 3.1.3 on 2021-02-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0018_auto_20210203_1535'),
        ('essentials', '0018_auto_20210203_1609'),
    ]

    operations = [
    ]
