# Generated by Django 3.1.5 on 2021-01-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0018_color_color_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color_tag',
        ),
    ]
