# Generated by Django 3.1.3 on 2021-03-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0019_auto_20210315_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='row_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
