# Generated by Django 3.1.5 on 2021-01-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0019_remove_color_color_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['color']},
        ),
    ]
