# Generated by Django 3.1.3 on 2020-12-31 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0020_size_row_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['row_no']},
        ),
        migrations.RemoveField(
            model_name='variant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='updated_at',
        ),
    ]
