# Generated by Django 3.1.5 on 2021-01-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0019_auto_20210121_0953'),
        ('essentials', '0020_auto_20210120_1743'),
    ]

    operations = [
    ]
