# Generated by Django 3.1.3 on 2021-02-25 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0022_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
