# Generated by Django 3.1.3 on 2021-02-25 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0024_auto_20210225_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='uuid',
        ),
    ]
