# Generated by Django 3.1.3 on 2021-02-25 23:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0025_remove_design_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='uuid2',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
