# Generated by Django 3.1.3 on 2021-02-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0026_design_uuid2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='uuid2',
        ),
    ]
