# Generated by Django 3.1.3 on 2021-02-26 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0027_remove_design_uuid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
