# Generated by Django 3.1.3 on 2021-02-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0028_variant_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='uuid',
        ),
    ]
