# Generated by Django 3.1.3 on 2021-02-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0029_remove_variant_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='uuid3',
            field=models.UUIDField(null=True),
        ),
    ]
