# Generated by Django 3.1.3 on 2021-02-27 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0030_design_uuid3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid3',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
