# Generated by Django 3.1.3 on 2021-02-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0031_auto_20210227_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid3',
            field=models.UUIDField(null=True),
        ),
    ]
