# Generated by Django 3.1.3 on 2021-02-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0034_auto_20210227_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='end_product_img',
            field=models.ImageField(blank=True, null=True, upload_to='end_product_imgs/'),
        ),
    ]
