# Generated by Django 3.1.3 on 2021-02-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0035_auto_20210227_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
