# Generated by Django 3.1.3 on 2020-11-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_seller_email_confirmed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
