# Generated by Django 3.1.3 on 2020-12-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
    ]
