# Generated by Django 3.1.3 on 2021-01-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
