# Generated by Django 3.1.3 on 2021-01-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='palcement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
