# Generated by Django 3.1.3 on 2021-02-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bundle2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='tasarimlar.design'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_digital_product2',
            field=models.BooleanField(default=False),
        ),
    ]
