# Generated by Django 3.1.5 on 2021-01-22 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='json_data',
        ),
    ]
