# Generated by Django 3.1.5 on 2021-03-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_type',
            new_name='product_type1',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_type2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
