# Generated by Django 3.1.3 on 2021-01-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_palcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='palcement',
            new_name='placement',
        ),
    ]
