# Generated by Django 3.1.3 on 2021-02-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210223_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='bundle',
            new_name='bundle1',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_digital_product',
            new_name='is_digital_product1',
        ),
    ]
