# Generated by Django 3.1.5 on 2021-01-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
