# Generated by Django 3.1.3 on 2021-01-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='json',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='json_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
