# Generated by Django 3.1.5 on 2021-03-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210301_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_type2',
            new_name='product_type',
        ),
    ]
