# Generated by Django 3.1.3 on 2021-02-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='downloadable_product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_digital_product',
            field=models.BooleanField(default=False),
        ),
    ]
