# Generated by Django 3.1.3 on 2021-01-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210121_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
