# Generated by Django 3.1.5 on 2021-01-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210123_1539'),
        ('orders', '0003_orderitem_json_data'),
    ]

    operations = [
    ]
