# Generated by Django 3.1.3 on 2020-12-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201218_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='design',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='end_product_img',
            field=models.ImageField(blank=True, null=True, upload_to='end_product_imgs/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/'),
        ),
    ]
