# Generated by Django 3.1.3 on 2021-01-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210121_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='json_data',
            new_name='json',
        ),
    ]
