# Generated by Django 3.1.3 on 2021-01-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_merge_20210123_1555'),
        ('orders', '0004_auto_20210123_1558'),
    ]

    operations = [
    ]
