# Generated by Django 3.1.5 on 2021-03-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_product_type4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_type1',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_type3',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_type4',
        ),
    ]
