# Generated by Django 3.1.3 on 2020-12-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
