# Generated by Django 3.1.3 on 2021-01-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210123_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='log_entry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
