# Generated by Django 3.1.3 on 2021-01-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
