# Generated by Django 3.1.5 on 2021-03-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210301_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_type3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
