# Generated by Django 3.1.3 on 2021-01-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_log_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ready_to_ship',
            field=models.BooleanField(default=False),
        ),
    ]
