# Generated by Django 3.1.5 on 2021-03-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_product_type3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_type3',
            new_name='product_type',
        ),
    ]
