# Generated by Django 3.1.3 on 2021-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210223_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
