# Generated by Django 3.1.5 on 2021-03-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210301_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_type1',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_type2',
        ),
    ]
