# Generated by Django 3.1.3 on 2021-02-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210204_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unkown or quations marks indicates order has been cancelled', max_digits=10, null=True),
        ),
    ]
