# Generated by Django 3.1.3 on 2021-02-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210204_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(blank=True, default=False, help_text='Unkown or question mark indicates that order has been cancelled', null=True),
        ),
    ]
