# Generated by Django 3.1.3 on 2021-02-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20210204_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment',
            field=models.BooleanField(blank=True, default=False, help_text='Customer will be notified via email when marked. Unknown or question mark indicateds order has been cancelled', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
