# Generated by Django 3.1.3 on 2021-02-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20210204_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(True, 'Fulfilled'), (False, 'In Progress'), (None, 'Cancelled')], default=False, max_length=20),
        ),
    ]
