# Generated by Django 3.1.3 on 2021-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment',
            field=models.BooleanField(default=False, help_text='Customer will be notified via email when marked. Unknown or question mark indicateds order has been cancelled'),
        ),
    ]
