# Generated by Django 3.1.3 on 2021-02-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210204_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[(True, 'Fulfilled'), (False, 'In Progress'), (None, 'Cancelled')], max_length=20, null=True),
        ),
    ]
