# Generated by Django 3.1.3 on 2021-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20210204_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Fulfilled'), (2, 'In Progress'), (3, 'Cancelled')], default=2),
        ),
    ]
