# Generated by Django 3.1.3 on 2021-02-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
