# Generated by Django 3.1.3 on 2021-02-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20210205_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Queue'), (2, 'In Progress'), (3, 'Fulfilled'), (4, 'Cancelled')], default='1'),
        ),
    ]
