# Generated by Django 3.1.3 on 2021-02-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20210212_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='json_data',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
