# Generated by Django 3.1.3 on 2021-02-23 21:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
