# Generated by Django 3.1.3 on 2021-02-22 21:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='id',
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
