# Generated by Django 3.1.3 on 2021-02-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0002_design_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
