# Generated by Django 3.1.3 on 2021-02-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0002_auto_20210222_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='designimage',
            name='tasarim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_images2', to='tasarimlar.design'),
        ),
    ]
