# Generated by Django 3.1.3 on 2021-02-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0003_designimage_tasarim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designimage',
            name='design',
        ),
    ]
