# Generated by Django 3.1.3 on 2021-02-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0003_design_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
