# Generated by Django 3.1.3 on 2021-02-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0004_remove_designimage_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='categories',
        ),
        migrations.AlterField(
            model_name='designimage',
            name='tasarim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_images', to='tasarimlar.design'),
        ),
    ]
