# Generated by Django 3.1.3 on 2021-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0004_auto_20210224_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(help_text='Image for preview. Will be display on list page', null=True, upload_to='images/'),
        ),
    ]
