# Generated by Django 3.1.3 on 2021-02-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0005_auto_20210224_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designimage',
            options={'ordering': ['row_no'], 'verbose_name': 'image', 'verbose_name_plural': 'gallery'},
        ),
    ]
