# Generated by Django 3.1.3 on 2021-02-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0005_auto_20210222_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designimage',
            name='tasarim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_images', to='tasarimlar.design'),
        ),
    ]
