# Generated by Django 3.1.3 on 2021-02-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0006_auto_20210222_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='tasarimlar.design_category'),
        ),
    ]
