# Generated by Django 3.1.3 on 2021-02-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasarimlar', '0007_design_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='category',
        ),
        migrations.AddField(
            model_name='design',
            name='departments',
            field=models.ManyToManyField(null=True, related_name='designs', to='tasarimlar.Design_Category'),
        ),
    ]
