# Generated by Django 3.1.3 on 2021-02-09 23:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Wage', 'Wage'), ('Rent', 'Rent'), ('Utility', 'Utility'), ('Other', 'Other')], default='Wage', max_length=10)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='amount of expense', max_digits=12)),
                ('invoice', models.FileField(blank=True, help_text='Upload PDF format of the invoice', null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
