# Generated by Django 3.1.3 on 2021-01-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0003_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Placement',
        ),
        migrations.DeleteModel(
            name='PlacementBase',
        ),
    ]
