# Generated by Django 3.1.3 on 2020-12-15 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0006_color_color_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='code',
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='item_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='essentials.color'),
        ),
    ]
