# Generated by Django 3.1.3 on 2020-12-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0009_auto_20201231_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='group',
            field=models.CharField(help_text='e.g. black adult tshirts, black youth tshirts, black hoodies (this field only for admins and not visible to customers)', max_length=40),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(help_text='e.g black (this field is visible to customers)', max_length=40),
        ),
    ]
