# Generated by Django 3.1.3 on 2021-01-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0009_auto_20210115_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Method',
        ),
    ]
