# Generated by Django 3.1.3 on 2020-12-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0010_auto_20201231_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='group',
            field=models.CharField(blank=True, help_text='e.g. black adult tshirts, black youth tshirts, black hoodies (this field only for admins and not visible to customers)', max_length=40, null=True),
        ),
    ]
