# Generated by Django 3.1.3 on 2020-12-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0011_auto_20201231_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
