# Generated by Django 3.1.3 on 2020-12-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0013_auto_20201231_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['row_no']},
        ),
        migrations.AddField(
            model_name='size',
            name='row_no',
            field=models.IntegerField(default=0),
        ),
    ]
