# Generated by Django 3.1.3 on 2020-12-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0017_size_row_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['row_no']},
        ),
    ]
