# Generated by Django 3.1.3 on 2020-12-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0019_auto_20201231_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='row_no',
            field=models.IntegerField(default=0),
        ),
    ]
